### ISSUE TITLE
可不可以总结一下BDFS和recursion？

### ISSUE THREAD

**Issue by sdbzcm** [awangdev/LintCode#11]
你好，无意中看到了你的这个文章，作为一个对coding完全不开窍的人来说，如获珍宝，谢谢分享。先刚尝试刷题，对任何题目都没有什么思路，无从下手，可不可以传授一点经验？recursion完全不懂，BDFS也不懂，可不可以开个专题讲一下对一个题目为什么我就需要用recursion和BDFS，如果用参数怎么定义？方法体怎么去思考写出来？谢谢

**Comment by awangdev** [comment]
Recursion, bfs, dfs 的基本知识, 应该先去网上读wiki, 或者online course, 然后再考虑什么适合用什么, 以及如何思考. 
等你读完了基本概念开始刷题, 可以参考: https://github.com/awangdev/LintCode/blob/master/KnowledgeHash.md#search

**Comment by sdbzcm** [comment]
谢谢，基本概念知道，就是理解不透，不会应用，不知道如何用来解题，一个题目拿过来不知道从哪个方面着手考虑用什么方法

**Comment by awangdev** [comment]
我觉得大家应该都有这样的困惑吧. 最好的方式就是多做题多总结; 捷径就是看别人的总结, 然后多做题, 多总结.

比如在遇到一个问题的时候, 你可能知道DFS的解法, 也知道BFS解法,那么:
- 如果是找到`shortest path`, 那么可以优先考虑BFS, 因为breadth-first-search 是一层一层地搜, shortest path一定会找到, 并且可能更早找到.
- 如果是要找到`all possible answers` 那么DFS可能更加适合: 反正都是要output所有答案, dfs有时候更好写一点, recursion嘛.
- follow-up可能问: 如果dfs recursion的复杂度很高, 也就意味着所有的runtime recursive calls都要存在stack memory里面, 那么很可能memory不够用那; 有时候即便是dfs里面track了visited, 也还是可能太大, 那么这时候可能要考虑用回bfs. bfs反正是普通的function call, 所有的big-O space用的都是heap memory, 所以限制稍微好一点.

这些就是一些用bfs, dfs的基本想法, 但并不是全部. 你自己做的时候, 可以有这样的总结呀!
