### ISSUE TITLE
A+B...不会溢出么？

### ISSUE THREAD

**Issue by sooner0493** [awangdev/LintCode#2]
(Integer.MAX_VALUE,100)

**Comment by awangdev** [comment]
Good point. 我觉得问到这个问题的时候, 可以提出来，要不要用一个long to catch the final result. 
一开始来一个 long result = a, 然后把接下去代码里面的a都写成result就行了吧. （https://github.com/shawnfan/LintCode/blob/master/Java/A+B.java）

如果大家都assume 不会溢出, 那就这么用a 作为结果。

**Comment by sooner0493** [comment]
我也是这么改的。。
