### ISSUE TITLE
Trapping Rain Water II.java  元素重复放入

### ISSUE THREAD

**Issue by lttzzlll** [awangdev/LintCode#7]
Trapping Rain Water II.java 90-110行，四个角上的元素是不是被重复放入了。但是不影响结果的正确性。

**Comment by Vjax** [comment]
Swap Nodes in Pairs.java 53行有问题   改成head.next=n2 就对了

**Comment by awangdev** [comment]
@lttzzlll 是的, 四个角重复放了. [visited check](https://github.com/awangdev/LintCode/blob/84351c38743f2682b98a2468f6c17bb5e880c34c/Java/Trapping%20Rain%20Water%20II.java#L111) 确保不会重复visit, 所以不影响结果.

**Comment by awangdev** [comment]
@Vjax 是的. 没错, 改掉了. 谢谢!
